// <auto-generated />
using System;
using GoTravelTour.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GoTravelTour.Migrations
{
    [DbContext(typeof(GoTravelDBContext))]
    [Migration("20191212021842_addAlojActVehiculos")]
    partial class addAlojActVehiculos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GoTravelTour.Models.AlmacenImagenes", b =>
                {
                    b.Property<int>("AlmacenImagenesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageContent");

                    b.Property<string>("Localizacion");

                    b.Property<string>("NombreImagen");

                    b.Property<string>("TipoImagen");

                    b.HasKey("AlmacenImagenesId");

                    b.ToTable("AlmacenImagenes");
                });

            modelBuilder.Entity("GoTravelTour.Models.CategoriaComodidad", b =>
                {
                    b.Property<int>("CategoriaComodidadId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("CategoriaComodidadId");

                    b.ToTable("CategoriaComodidades");
                });

            modelBuilder.Entity("GoTravelTour.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Calle");

                    b.Property<string>("Ciudad");

                    b.Property<string>("Correo");

                    b.Property<double?>("Descuento");

                    b.Property<string>("Direccion");

                    b.Property<string>("Estado");

                    b.Property<string>("ImageContent");

                    b.Property<string>("ImageMimeType");

                    b.Property<string>("ImageName");

                    b.Property<bool>("IsActivo");

                    b.Property<bool>("IsPublic");

                    b.Property<string>("Localizador");

                    b.Property<string>("Nombre");

                    b.Property<string>("Pais");

                    b.Property<string>("Telefono");

                    b.Property<string>("TipoTrasaccion");

                    b.Property<string>("ZipCode");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("GoTravelTour.Models.CombinacionHuespedes", b =>
                {
                    b.Property<int>("CombinacionHuespedesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantAdult");

                    b.Property<int>("CantInfantes");

                    b.Property<int>("CantNino");

                    b.Property<int?>("HabitacionId");

                    b.Property<bool>("IsActivo");

                    b.Property<int>("ProductoId");

                    b.HasKey("CombinacionHuespedesId");

                    b.HasIndex("HabitacionId");

                    b.HasIndex("ProductoId");

                    b.ToTable("CombinacionHuespedes");
                });

            modelBuilder.Entity("GoTravelTour.Models.Comodidades", b =>
                {
                    b.Property<int>("ComodidadesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoriaComodidadId");

                    b.Property<string>("Nombre");

                    b.HasKey("ComodidadesId");

                    b.HasIndex("CategoriaComodidadId");

                    b.ToTable("Comodidades");
                });

            modelBuilder.Entity("GoTravelTour.Models.ComodidadesProductos", b =>
                {
                    b.Property<int>("ComodidadesProductosId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ComodidadesId");

                    b.Property<int>("ProductoId");

                    b.HasKey("ComodidadesProductosId");

                    b.HasIndex("ComodidadesId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ComodidadesProductos");
                });

            modelBuilder.Entity("GoTravelTour.Models.Contrato", b =>
                {
                    b.Property<int>("ContratoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoOfertaEspecial");

                    b.Property<DateTime?>("FechaFinBooking");

                    b.Property<DateTime?>("FechaFinTravel");

                    b.Property<DateTime?>("FechaInicioBooking");

                    b.Property<DateTime?>("FechaInicioTravel");

                    b.Property<bool>("IsActivo");

                    b.Property<string>("Nombre");

                    b.Property<bool>("OfertaEspecial");

                    b.Property<int>("TipoProductoId");

                    b.HasKey("ContratoId");

                    b.HasIndex("TipoProductoId");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("GoTravelTour.Models.Distribuidor", b =>
                {
                    b.Property<int>("DistribuidorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("DistribuidorId");

                    b.ToTable("Distribuidores");
                });

            modelBuilder.Entity("GoTravelTour.Models.Habitacion", b =>
                {
                    b.Property<int>("HabitacionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<bool>("IsActiva");

                    b.Property<bool>("IsPayPerRoom");

                    b.Property<int>("ProductoId");

                    b.Property<string>("SKU");

                    b.Property<int>("TipoHabitacionId");

                    b.HasKey("HabitacionId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TipoHabitacionId");

                    b.ToTable("Habitaciones");
                });

            modelBuilder.Entity("GoTravelTour.Models.Modificador", b =>
                {
                    b.Property<int>("ModificadorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantAdult");

                    b.Property<int>("CantInfantes");

                    b.Property<int>("CantNino");

                    b.Property<int>("ContratoId");

                    b.Property<DateTime?>("FechaF");

                    b.Property<DateTime?>("FechaI");

                    b.Property<string>("IdentificadorModificador");

                    b.Property<bool>("IsActivo");

                    b.Property<int?>("PrecioAlojamientoId");

                    b.Property<string>("TipoModificadorPrecio");

                    b.Property<int?>("TipoProductoId");

                    b.HasKey("ModificadorId");

                    b.HasIndex("ContratoId");

                    b.HasIndex("PrecioAlojamientoId");

                    b.HasIndex("TipoProductoId");

                    b.ToTable("Modificadores");
                });

            modelBuilder.Entity("GoTravelTour.Models.ModificadorProductos", b =>
                {
                    b.Property<int>("ModificadorProductosId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ModificadorId");

                    b.Property<int?>("ProductoId");

                    b.HasKey("ModificadorProductosId");

                    b.HasIndex("ModificadorId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ModificadorProductos");
                });

            modelBuilder.Entity("GoTravelTour.Models.NombreTemporada", b =>
                {
                    b.Property<int>("NombreTemporadaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("NombreTemporadaId");

                    b.ToTable("NombreTemporadas");
                });

            modelBuilder.Entity("GoTravelTour.Models.PlanesAlimenticios", b =>
                {
                    b.Property<int>("PlanesAlimenticiosId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo");

                    b.Property<string>("Nombre");

                    b.HasKey("PlanesAlimenticiosId");

                    b.ToTable("PlanesAlimenticios");
                });

            modelBuilder.Entity("GoTravelTour.Models.PosibleCombinacion", b =>
                {
                    b.Property<int>("PosibleCombinacionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantAdult");

                    b.Property<int>("CantInfantes");

                    b.Property<int>("CantNino");

                    b.Property<int>("TipoHabitacionId");

                    b.HasKey("PosibleCombinacionId");

                    b.HasIndex("TipoHabitacionId");

                    b.ToTable("PosibleCombinaciones");
                });

            modelBuilder.Entity("GoTravelTour.Models.PrecioActividad", b =>
                {
                    b.Property<int>("PrecioActividadId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContratoId");

                    b.Property<int>("HorasAdicionales");

                    b.Property<double>("Incluido");

                    b.Property<double>("PrecioAdulto");

                    b.Property<double>("PrecioInfante");

                    b.Property<double>("PrecioNino");

                    b.Property<int>("ProductoId");

                    b.Property<int?>("TemporadaId");

                    b.HasKey("PrecioActividadId");

                    b.HasIndex("ContratoId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TemporadaId");

                    b.ToTable("PrecioActividades");
                });

            modelBuilder.Entity("GoTravelTour.Models.PrecioAlojamiento", b =>
                {
                    b.Property<int>("PrecioAlojamientoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContratoId");

                    b.Property<int?>("HabitacionId");

                    b.Property<double>("Precio");

                    b.Property<int>("ProductoId");

                    b.Property<int?>("TemporadaId");

                    b.HasKey("PrecioAlojamientoId");

                    b.HasIndex("ContratoId");

                    b.HasIndex("HabitacionId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TemporadaId");

                    b.ToTable("PrecioAlojamiento");
                });

            modelBuilder.Entity("GoTravelTour.Models.PrecioComodidades", b =>
                {
                    b.Property<int>("PrecioComodidadesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ComodidadesId");

                    b.Property<int>("ProductoId");

                    b.HasKey("PrecioComodidadesId");

                    b.HasIndex("ComodidadesId");

                    b.HasIndex("ProductoId");

                    b.ToTable("PrecioComodidades");
                });

            modelBuilder.Entity("GoTravelTour.Models.PrecioPlanesAlimenticios", b =>
                {
                    b.Property<int>("PrecioPlanesAlimenticiosId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContratoId");

                    b.Property<double>("Precio");

                    b.Property<int>("ProductoId");

                    b.Property<int?>("TemporadaId");

                    b.HasKey("PrecioPlanesAlimenticiosId");

                    b.HasIndex("ContratoId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TemporadaId");

                    b.ToTable("PrecioPlanesAlimenticios");
                });

            modelBuilder.Entity("GoTravelTour.Models.PrecioRentaAutos", b =>
                {
                    b.Property<int>("PrecioRentaAutosId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContratoId");

                    b.Property<int>("DiasExtra");

                    b.Property<double>("Precio");

                    b.Property<int>("ProductoId");

                    b.Property<double>("Seguro");

                    b.Property<int?>("TemporadaId");

                    b.HasKey("PrecioRentaAutosId");

                    b.HasIndex("ContratoId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TemporadaId");

                    b.ToTable("PrecioRentaAutos");
                });

            modelBuilder.Entity("GoTravelTour.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescripcionCorta");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<bool>("IsActivo");

                    b.Property<string>("Latitud");

                    b.Property<string>("Longitud");

                    b.Property<string>("Nombre");

                    b.Property<string>("Notas");

                    b.Property<bool>("PermiteAdult");

                    b.Property<bool>("PermiteHacerCopia");

                    b.Property<bool>("PermiteInfante");

                    b.Property<bool>("PermiteNino");

                    b.Property<int>("ProveedorId");

                    b.Property<int>("PuntoInteresId");

                    b.Property<int>("RegionId");

                    b.Property<string>("SKU");

                    b.Property<int>("TipoProductoId");

                    b.HasKey("ProductoId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("PuntoInteresId");

                    b.HasIndex("RegionId");

                    b.HasIndex("TipoProductoId");

                    b.ToTable("Productos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Producto");
                });

            modelBuilder.Entity("GoTravelTour.Models.ProductoDistribuidor", b =>
                {
                    b.Property<int>("ProductoDistribuidorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DistribuidorId");

                    b.Property<int>("ProductoId");

                    b.HasKey("ProductoDistribuidorId");

                    b.HasIndex("DistribuidorId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductoDistribuidores");
                });

            modelBuilder.Entity("GoTravelTour.Models.Proveedor", b =>
                {
                    b.Property<int>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Correo");

                    b.Property<string>("Nombre");

                    b.Property<string>("Telefono");

                    b.HasKey("ProveedorId");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("GoTravelTour.Models.PuntoInteres", b =>
                {
                    b.Property<int>("PuntoInteresId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.Property<int?>("RegionId");

                    b.HasKey("PuntoInteresId");

                    b.HasIndex("RegionId");

                    b.ToTable("PuntosInteres");
                });

            modelBuilder.Entity("GoTravelTour.Models.RangoFechas", b =>
                {
                    b.Property<int>("RangoFechasId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaFin");

                    b.Property<DateTime>("FechaInicio");

                    b.Property<int>("TemporadaId");

                    b.HasKey("RangoFechasId");

                    b.HasIndex("TemporadaId");

                    b.ToTable("RangoFechas");
                });

            modelBuilder.Entity("GoTravelTour.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("RegionId");

                    b.ToTable("Regiones");
                });

            modelBuilder.Entity("GoTravelTour.Models.Reglas", b =>
                {
                    b.Property<int>("ReglasId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActivo");

                    b.Property<int>("ModificadorId");

                    b.Property<double>("PrecioFijo");

                    b.Property<double>("PrecioPorCiento");

                    b.Property<int>("TipoHabitacionId");

                    b.Property<string>("TipoPersona");

                    b.Property<string>("TipoPrecioHabitacion");

                    b.HasKey("ReglasId");

                    b.HasIndex("ModificadorId");

                    b.HasIndex("TipoHabitacionId");

                    b.ToTable("Reglas");
                });

            modelBuilder.Entity("GoTravelTour.Models.RestriccionesActividad", b =>
                {
                    b.Property<int>("RestriccionesActividadId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContratoId");

                    b.Property<bool>("IsActivo");

                    b.Property<int>("Maximo");

                    b.Property<int>("Minimo");

                    b.Property<double>("Precio");

                    b.Property<int>("ProductoId");

                    b.Property<int?>("TemporadaId");

                    b.HasKey("RestriccionesActividadId");

                    b.HasIndex("ContratoId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TemporadaId");

                    b.ToTable("RestriccionesActividades");
                });

            modelBuilder.Entity("GoTravelTour.Models.RestriccionesRentasAutos", b =>
                {
                    b.Property<int>("RestriccionesRentasAutosId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContratoId");

                    b.Property<bool>("IsActivo");

                    b.Property<int>("Maximo");

                    b.Property<int>("Minimo");

                    b.Property<double>("Precio");

                    b.Property<int>("ProductoId");

                    b.Property<int?>("TemporadaId");

                    b.HasKey("RestriccionesRentasAutosId");

                    b.HasIndex("ContratoId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TemporadaId");

                    b.ToTable("RestriccionesRentasAutos");
                });

            modelBuilder.Entity("GoTravelTour.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreRol");

                    b.HasKey("RolId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GoTravelTour.Models.Rutas", b =>
                {
                    b.Property<int>("RutasId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("puntoDestinoPuntoInteresId");

                    b.Property<int?>("puntoOrigenPuntoInteresId");

                    b.Property<int?>("regionDestinoRegionId");

                    b.Property<int?>("regionOrigenRegionId");

                    b.HasKey("RutasId");

                    b.HasIndex("puntoDestinoPuntoInteresId");

                    b.HasIndex("puntoOrigenPuntoInteresId");

                    b.HasIndex("regionDestinoRegionId");

                    b.HasIndex("regionOrigenRegionId");

                    b.ToTable("Rutas");
                });

            modelBuilder.Entity("GoTravelTour.Models.Temporada", b =>
                {
                    b.Property<int>("TemporadaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContratoId");

                    b.Property<string>("Nombre");

                    b.HasKey("TemporadaId");

                    b.HasIndex("ContratoId");

                    b.ToTable("Temporadas");
                });

            modelBuilder.Entity("GoTravelTour.Models.TipoAlojamiento", b =>
                {
                    b.Property<int>("TipoAlojamientoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("TipoAlojamientoId");

                    b.ToTable("TipoAlojamientos");
                });

            modelBuilder.Entity("GoTravelTour.Models.TipoHabitacion", b =>
                {
                    b.Property<int>("TipoHabitacionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("TipoHabitacionId");

                    b.ToTable("TipoHabitaciones");
                });

            modelBuilder.Entity("GoTravelTour.Models.TipoProducto", b =>
                {
                    b.Property<int>("TipoProductoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("TipoProductoId");

                    b.ToTable("TipoProductos");
                });

            modelBuilder.Entity("GoTravelTour.Models.TipoTransporte", b =>
                {
                    b.Property<int>("TipoTransporteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("TipoTransporteId");

                    b.ToTable("TipoTransportes");
                });

            modelBuilder.Entity("GoTravelTour.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteId");

                    b.Property<string>("Correo");

                    b.Property<bool>("IsActivo");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<int>("RolId");

                    b.Property<string>("Telefono");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("UsuarioId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GoTravelTour.Models.Alojamiento", b =>
                {
                    b.HasBaseType("GoTravelTour.Models.Producto");

                    b.Property<int>("AlojamientoId");

                    b.Property<int>("Categoria");

                    b.Property<int>("TipoAlojamientoId");

                    b.HasIndex("TipoAlojamientoId");

                    b.ToTable("Alojamiento");

                    b.HasDiscriminator().HasValue("Alojamiento");
                });

            modelBuilder.Entity("GoTravelTour.Models.CombinacionHuespedes", b =>
                {
                    b.HasOne("GoTravelTour.Models.Habitacion", "Habitacion")
                        .WithMany()
                        .HasForeignKey("HabitacionId");

                    b.HasOne("GoTravelTour.Models.Producto", "Hotel")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoTravelTour.Models.Comodidades", b =>
                {
                    b.HasOne("GoTravelTour.Models.CategoriaComodidad", "CategoriaComodidad")
                        .WithMany()
                        .HasForeignKey("CategoriaComodidadId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoTravelTour.Models.ComodidadesProductos", b =>
                {
                    b.HasOne("GoTravelTour.Models.Comodidades", "Comodidades")
                        .WithMany()
                        .HasForeignKey("ComodidadesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoTravelTour.Models.Producto", "Producto")
                        .WithMany("ListaComodidades")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoTravelTour.Models.Contrato", b =>
                {
                    b.HasOne("GoTravelTour.Models.TipoProducto", "TipoProducto")
                        .WithMany()
                        .HasForeignKey("TipoProductoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoTravelTour.Models.Habitacion", b =>
                {
                    b.HasOne("GoTravelTour.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoTravelTour.Models.TipoHabitacion", "TipoHabitacion")
                        .WithMany()
                        .HasForeignKey("TipoHabitacionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoTravelTour.Models.Modificador", b =>
                {
                    b.HasOne("GoTravelTour.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoTravelTour.Models.PrecioAlojamiento")
                        .WithMany("Modificadores")
                        .HasForeignKey("PrecioAlojamientoId");

                    b.HasOne("GoTravelTour.Models.TipoProducto", "TipoProducto")
                        .WithMany()
                        .HasForeignKey("TipoProductoId");
                });

            modelBuilder.Entity("GoTravelTour.Models.ModificadorProductos", b =>
                {
                    b.HasOne("GoTravelTour.Models.Modificador", "Modificador")
                        .WithMany()
                        .HasForeignKey("ModificadorId");

                    b.HasOne("GoTravelTour.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId");
                });

            modelBuilder.Entity("GoTravelTour.Models.PosibleCombinacion", b =>
                {
                    b.HasOne("GoTravelTour.Models.TipoHabitacion", "TipoHabitacion")
                        .WithMany()
                        .HasForeignKey("TipoHabitacionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoTravelTour.Models.PrecioActividad", b =>
                {
                    b.HasOne("GoTravelTour.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId");

                    b.HasOne("GoTravelTour.Models.Producto", "Actividad")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoTravelTour.Models.Temporada", "Temporada")
                        .WithMany()
                        .HasForeignKey("TemporadaId");
                });

            modelBuilder.Entity("GoTravelTour.Models.PrecioAlojamiento", b =>
                {
                    b.HasOne("GoTravelTour.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId");

                    b.HasOne("GoTravelTour.Models.Habitacion", "Habitacion")
                        .WithMany()
                        .HasForeignKey("HabitacionId");

                    b.HasOne("GoTravelTour.Models.Producto", "Hotel")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoTravelTour.Models.Temporada", "Temporada")
                        .WithMany()
                        .HasForeignKey("TemporadaId");
                });

            modelBuilder.Entity("GoTravelTour.Models.PrecioComodidades", b =>
                {
                    b.HasOne("GoTravelTour.Models.Comodidades", "Comodidades")
                        .WithMany()
                        .HasForeignKey("ComodidadesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoTravelTour.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoTravelTour.Models.PrecioPlanesAlimenticios", b =>
                {
                    b.HasOne("GoTravelTour.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId");

                    b.HasOne("GoTravelTour.Models.Producto", "Hotel")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoTravelTour.Models.Temporada", "Temporada")
                        .WithMany()
                        .HasForeignKey("TemporadaId");
                });

            modelBuilder.Entity("GoTravelTour.Models.PrecioRentaAutos", b =>
                {
                    b.HasOne("GoTravelTour.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId");

                    b.HasOne("GoTravelTour.Models.Producto", "Auto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoTravelTour.Models.Temporada", "Temporada")
                        .WithMany()
                        .HasForeignKey("TemporadaId");
                });

            modelBuilder.Entity("GoTravelTour.Models.Producto", b =>
                {
                    b.HasOne("GoTravelTour.Models.Proveedor", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoTravelTour.Models.PuntoInteres", "PuntoInteres")
                        .WithMany()
                        .HasForeignKey("PuntoInteresId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoTravelTour.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoTravelTour.Models.TipoProducto", "TipoProducto")
                        .WithMany()
                        .HasForeignKey("TipoProductoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoTravelTour.Models.ProductoDistribuidor", b =>
                {
                    b.HasOne("GoTravelTour.Models.Distribuidor", "Distribuidor")
                        .WithMany("ListaProductosDistribuidos")
                        .HasForeignKey("DistribuidorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoTravelTour.Models.Producto", "Producto")
                        .WithMany("ListaDistribuidoresProducto")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoTravelTour.Models.PuntoInteres", b =>
                {
                    b.HasOne("GoTravelTour.Models.Region", "Region")
                        .WithMany("PuntosDeInteres")
                        .HasForeignKey("RegionId");
                });

            modelBuilder.Entity("GoTravelTour.Models.RangoFechas", b =>
                {
                    b.HasOne("GoTravelTour.Models.Temporada", "Temporada")
                        .WithMany("ListaFechasTemporada")
                        .HasForeignKey("TemporadaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoTravelTour.Models.Reglas", b =>
                {
                    b.HasOne("GoTravelTour.Models.Modificador", "Modificador")
                        .WithMany()
                        .HasForeignKey("ModificadorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoTravelTour.Models.TipoHabitacion", "TipoHabitacion")
                        .WithMany()
                        .HasForeignKey("TipoHabitacionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoTravelTour.Models.RestriccionesActividad", b =>
                {
                    b.HasOne("GoTravelTour.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId");

                    b.HasOne("GoTravelTour.Models.Producto", "Actividad")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoTravelTour.Models.Temporada", "Temporada")
                        .WithMany()
                        .HasForeignKey("TemporadaId");
                });

            modelBuilder.Entity("GoTravelTour.Models.RestriccionesRentasAutos", b =>
                {
                    b.HasOne("GoTravelTour.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId");

                    b.HasOne("GoTravelTour.Models.Producto", "Auto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoTravelTour.Models.Temporada", "Temporada")
                        .WithMany()
                        .HasForeignKey("TemporadaId");
                });

            modelBuilder.Entity("GoTravelTour.Models.Rutas", b =>
                {
                    b.HasOne("GoTravelTour.Models.PuntoInteres", "puntoDestino")
                        .WithMany()
                        .HasForeignKey("puntoDestinoPuntoInteresId");

                    b.HasOne("GoTravelTour.Models.PuntoInteres", "puntoOrigen")
                        .WithMany()
                        .HasForeignKey("puntoOrigenPuntoInteresId");

                    b.HasOne("GoTravelTour.Models.Region", "regionDestino")
                        .WithMany()
                        .HasForeignKey("regionDestinoRegionId");

                    b.HasOne("GoTravelTour.Models.Region", "regionOrigen")
                        .WithMany()
                        .HasForeignKey("regionOrigenRegionId");
                });

            modelBuilder.Entity("GoTravelTour.Models.Temporada", b =>
                {
                    b.HasOne("GoTravelTour.Models.Contrato", "Contrato")
                        .WithMany("Temporadas")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoTravelTour.Models.Usuario", b =>
                {
                    b.HasOne("GoTravelTour.Models.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GoTravelTour.Models.Rol", "rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoTravelTour.Models.Alojamiento", b =>
                {
                    b.HasOne("GoTravelTour.Models.TipoAlojamiento", "TipoAlojamiento")
                        .WithMany()
                        .HasForeignKey("TipoAlojamientoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
